# Generated by Django 2.2.6 on 2019-10-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='事件类型标题')),
                ('level', models.IntegerField(default=1, verbose_name='事件级别')),
                ('parent_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_time.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='事情标题')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('duration', models.IntegerField(default=0, verbose_name='持续时间')),
                ('happiness', models.IntegerField(default=0, verbose_name='幸福度')),
                ('health', models.IntegerField(default=0, verbose_name='健康值')),
                ('fulfillment', models.IntegerField(default=0, verbose_name='成就感')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_time.Event', verbose_name='事件类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.UserInfo', verbose_name='用户')),
            ],
        ),
    ]
