# Generated by Django 2.2.6 on 2019-12-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_time.Event'),
        ),
    ]
