# Generated by Django 2.2.6 on 2019-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_time', '0002_auto_20191203_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='FFFFFF', max_length=6, verbose_name='颜色配置'),
        ),
    ]
