# Generated by Django 2.2.6 on 2019-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_time', '0003_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='颜色配置'),
        ),
    ]
