# Generated by Django 2.2.6 on 2019-12-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者的姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='出版社的名称')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='图书名称')),
                ('category', models.IntegerField(choices=[(1, 'Python'), (2, 'Go'), (3, 'Linux')], verbose_name='图书的类别')),
                ('pub_time', models.DateField(verbose_name='图书的出版日期')),
                ('author', models.ManyToManyField(to='app_test.Author')),
                ('publisher', models.ForeignKey(on_delete=None, to='app_test.Publisher')),
            ],
        ),
    ]
